/**
 * ANCHOR SECURITY PLATFORM - AI Evolution Dashboard
 * 
 * This dashboard shows the AI Evolution Engine status and provides
 * controls to manage Anchor's autonomous security updates.
 */

import { useState, useEffect, useRef, useCallback } from 'react';
import { backendApi } from '../utils/backendApi';

// Real-time event from SSE stream
interface LiveEvent {
  type: string;
  data: Record<string, unknown>;
  timestamp: string;
}

interface EvolutionStatus {
  lastUpdate: string;
  threatsProcessed: number;
  rulesGenerated: number;
  updatesApplied: number;
  nextScheduledUpdate: string;
  aiAnalysisCount: number;
  competitiveScore: number;
}

interface ThreatIntel {
  id: string;
  source: string;
  type: string;
  severity: string;
  title: string;
  description: string;
  timestamp: string;
  processed: boolean;
  aiAnalysis?: string;
}

interface DetectionRule {
  id: string;
  name: string;
  type: string;
  pattern: string;
  severity: string;
  enabled: boolean;
  autoGenerated: boolean;
  createdAt: string;
  effectiveness: number;
}

interface EvolutionLogEntry {
  timestamp: string;
  action: string;
  details: string;
  aiGenerated: boolean;
}

export default function AIEvolutionDashboard() {
  const [activeTab, setActiveTab] = useState<'live' | 'overview' | 'threats' | 'rules' | 'feeds' | 'generate'>('live');
  const [loading, setLoading] = useState(true);
  const [status, setStatus] = useState<EvolutionStatus | null>(null);
  const [threats, setThreats] = useState<ThreatIntel[]>([]);
  const [rules, setRules] = useState<DetectionRule[]>([]);
  const [evolutionLog, setEvolutionLog] = useState<EvolutionLogEntry[]>([]);
  const [isEvolving, setIsEvolving] = useState(false);
  const [analysisResult, setAnalysisResult] = useState<string | null>(null);
  const [moduleRequirement, setModuleRequirement] = useState('');
  const [generatedModule, setGeneratedModule] = useState<any>(null);
  const [competitiveAnalysis, setCompetitiveAnalysis] = useState<any>(null);
  
  // Real-time live feed
  const [liveEvents, setLiveEvents] = useState<LiveEvent[]>([]);
  const [isConnected, setIsConnected] = useState(false);
  const [liveStats, setLiveStats] = useState({ totalThreats: 0, totalRules: 0, aiAnalysisCount: 0, competitiveScore: 95 });
  const eventSourceRef = useRef<EventSource | null>(null);
  const liveLogRef = useRef<HTMLDivElement>(null);


  const [isBootstrapping, setIsBootstrapping] = useState(false);

  // SSE connection for real-time streaming
  useEffect(() => {
    const apiBase = import.meta.env.VITE_API_URL || 'http://localhost:3001/api';
    // Only connect SSE on localhost (backend must be reachable)
    const isLocalhost = apiBase.includes('localhost') || apiBase.includes('127.0.0.1');
    if (!isLocalhost) return;

    const token = localStorage.getItem('auth_token') || sessionStorage.getItem('auth_token') || '';
    
    const connectSSE = () => {
      try {
        const es = new EventSource(`${apiBase}/ai-evolution/stream?token=${token}`);
        eventSourceRef.current = es;

        es.onopen = () => {
          setIsConnected(true);
          addLiveEvent({ type: 'system', data: { message: 'Connected to AI Evolution Engine' }, timestamp: new Date().toISOString() });
        };

        es.onmessage = (event) => {
          try {
            const parsed = JSON.parse(event.data) as LiveEvent;
            addLiveEvent(parsed);
            
            // Update live stats from heartbeats
            if (parsed.type === 'heartbeat' || parsed.type === 'connected') {
              const d = parsed.data as any;
              setLiveStats({
                totalThreats: d.totalThreats ?? d.status?.threatsProcessed ?? liveStats.totalThreats,
                totalRules: d.totalRules ?? liveStats.totalRules,
                aiAnalysisCount: d.aiAnalysisCount ?? d.status?.aiAnalysisCount ?? liveStats.aiAnalysisCount,
                competitiveScore: d.competitiveScore ?? d.status?.competitiveScore ?? liveStats.competitiveScore,
              });
            }
            
            // Update stats from cycle events
            if (parsed.type === 'cycle_complete') {
              const d = parsed.data as any;
              setLiveStats(prev => ({
                ...prev,
                totalThreats: d.totalThreats ?? prev.totalThreats,
                totalRules: d.totalRules ?? prev.totalRules,
              }));
              // Refresh full data after a cycle
              loadData();
            }
          } catch {
            // ignore parse errors
          }
        };

        es.onerror = () => {
          setIsConnected(false);
          es.close();
          // Reconnect after 5 seconds
          setTimeout(connectSSE, 5000);
        };
      } catch {
        // SSE not available, fall back to polling
        setIsConnected(false);
      }
    };

    connectSSE();

    return () => {
      eventSourceRef.current?.close();
    };
  }, []);

  const addLiveEvent = useCallback((event: LiveEvent) => {
    setLiveEvents(prev => [event, ...prev].slice(0, 200)); // Keep last 200 events
    // Auto-scroll
    setTimeout(() => {
      liveLogRef.current?.scrollTo({ top: 0, behavior: 'smooth' });
    }, 50);
  }, []);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    setLoading(true);
    try {
      const [statusRes, threatsRes, rulesRes, logRes] = await Promise.all([
        backendApi.aiEvolution.getStatus(),
        backendApi.aiEvolution.getThreats({ limit: 50 }),
        backendApi.aiEvolution.getRules(),
        backendApi.aiEvolution.getEvolutionLog(50)
      ]);

      setStatus((statusRes as any)?.status || null);
      setThreats((threatsRes as any)?.threats || []);
      setRules((rulesRes as any)?.rules || []);
      setEvolutionLog((logRes as any)?.log || []);
    } catch (error) {
      console.error('Failed to load AI Evolution data:', error);
    }
    setLoading(false);
  };

  const triggerEvolution = async () => {
    setIsEvolving(true);
    try {
      const result = await backendApi.aiEvolution.triggerEvolution(false);
      alert(`Evolution complete: ${(result as any).results.newThreats} new threats, ${(result as any).results.newRules} new rules from ${(result as any).results.sources?.length || 0} sources`);
      loadData();
    } catch (error) {
      console.error('Evolution failed:', error);
      alert('Evolution cycle failed');
    }
    setIsEvolving(false);
  };

  const bootstrapEngine = async () => {
    if (!confirm('BOOTSTRAP MODE: This will aggressively seed the AI with data from ALL 6 threat feeds, generate detection rules, and switch to 15-minute evolution cycles for 24 hours. Continue?')) return;
    setIsBootstrapping(true);
    try {
      const result = await backendApi.aiEvolution.bootstrap();
      const data = result as any;
      alert(`BOOTSTRAP COMPLETE!\n\n` +
        `Threats ingested: ${data.results.phase1_feeds.threats}\n` +
        `Rules generated: ${data.results.phase2_rules.generated}\n` +
        `Sources: ${data.results.phase1_feeds.sources.join(', ')}\n` +
        `Time: ${(data.results.totalTime / 1000).toFixed(1)}s\n\n` +
        `Engine is now in ACCELERATED mode (15-min cycles for 24h)`);
      loadData();
    } catch (error) {
      console.error('Bootstrap failed:', error);
      alert('Bootstrap failed — check console for details');
    }
    setIsBootstrapping(false);
  };

  const analyzeCustomQuery = async (query: string) => {
    try {
      const result = await backendApi.aiEvolution.analyze({ customQuery: query });
      setAnalysisResult((result as any).analysis);
    } catch (error) {
      console.error('Analysis failed:', error);
    }
  };

  const generateModule = async () => {
    if (!moduleRequirement.trim()) return;
    try {
      const result = await backendApi.aiEvolution.generateModule(moduleRequirement);
      setGeneratedModule((result as any).module);
    } catch (error) {
      console.error('Module generation failed:', error);
    }
  };

  const loadCompetitiveAnalysis = async () => {
    try {
      const result = await backendApi.aiEvolution.getCompetitiveAnalysis();
      setCompetitiveAnalysis(result);
    } catch (error) {
      console.error('Competitive analysis failed:', error);
    }
  };

  const toggleRule = async (ruleId: string, enabled: boolean) => {
    try {
      await backendApi.aiEvolution.toggleRule(ruleId, !enabled);
      setRules(rules.map(r => r.id === ruleId ? { ...r, enabled: !enabled } : r));
    } catch (error) {
      console.error('Failed to toggle rule:', error);
    }
  };

  const getEventConfig = (type: string): { icon: string; bg: string; border: string; ring: string; label: string } => {
    switch (type) {
      case 'cycle_start': return { icon: '🚀', bg: 'bg-blue-900/20', border: 'border-blue-800/30', ring: 'ring-blue-500/30', label: 'text-blue-400' };
      case 'feeds_fetching': return { icon: '📡', bg: 'bg-cyan-900/20', border: 'border-cyan-800/30', ring: 'ring-cyan-500/30', label: 'text-cyan-400' };
      case 'feed_success': return { icon: '✅', bg: 'bg-green-900/20', border: 'border-green-800/30', ring: 'ring-green-500/30', label: 'text-green-400' };
      case 'feed_error': return { icon: '❌', bg: 'bg-red-900/20', border: 'border-red-800/30', ring: 'ring-red-500/30', label: 'text-red-400' };
      case 'threat_ingested': return { icon: '🎯', bg: 'bg-orange-900/20', border: 'border-orange-800/30', ring: 'ring-orange-500/30', label: 'text-orange-400' };
      case 'ai_analyzing': return { icon: '🧠', bg: 'bg-purple-900/20', border: 'border-purple-800/30', ring: 'ring-purple-500/30', label: 'text-purple-400' };
      case 'rule_generated': return { icon: '🛡️', bg: 'bg-emerald-900/20', border: 'border-emerald-800/30', ring: 'ring-emerald-500/30', label: 'text-emerald-400' };
      case 'cycle_complete': return { icon: '🏁', bg: 'bg-indigo-900/20', border: 'border-indigo-800/30', ring: 'ring-indigo-500/30', label: 'text-indigo-400' };
      case 'heartbeat': return { icon: '💓', bg: 'bg-slate-800/20', border: 'border-slate-700/30', ring: 'ring-slate-500/30', label: 'text-slate-500' };
      case 'connected': return { icon: '🔗', bg: 'bg-green-900/20', border: 'border-green-800/30', ring: 'ring-green-500/30', label: 'text-green-400' };
      case 'system': return { icon: '⚙️', bg: 'bg-slate-800/20', border: 'border-slate-700/30', ring: 'ring-slate-500/30', label: 'text-slate-400' };
      default: return { icon: '📋', bg: 'bg-slate-800/20', border: 'border-slate-700/30', ring: 'ring-slate-500/30', label: 'text-slate-400' };
    }
  };

  const formatEventData = (event: LiveEvent): string => {
    const d = event.data as Record<string, unknown>;
    switch (event.type) {
      case 'cycle_start': return `Evolution cycle starting in ${d.mode} mode`;
      case 'feeds_fetching': return String(d.message || 'Fetching threat feeds...');
      case 'feed_success': return `${d.feed}: ${d.count} items ingested`;
      case 'feed_error': return `${d.feed}: ${d.error}`;
      case 'threat_ingested': return `[${d.severity}] ${d.title} (${d.source}) — Total in store: ${d.total}`;
      case 'ai_analyzing': return `Analyzing ${d.severity} threat: ${d.threat}`;
      case 'rule_generated': return `"${d.name}" (${d.type}, ${d.severity}) — Total rules: ${d.totalRules}`;
      case 'cycle_complete': return `${d.newThreats} threats, ${d.newRules} rules from ${d.sources} sources`;
      case 'heartbeat': return `Store: ${d.totalThreats} threats, ${d.totalRules} rules | Score: ${d.competitiveScore}%`;
      case 'connected': return 'Real-time stream connected to evolution engine';
      case 'system': return String(d.message || '');
      default: return JSON.stringify(d).substring(0, 120);
    }
  };

  const getSeverityColor = (severity: string) => {
    switch (severity.toLowerCase()) {
      case 'critical': return 'text-red-400 bg-red-500/20';
      case 'high': return 'text-orange-400 bg-orange-500/20';
      case 'medium': return 'text-yellow-400 bg-yellow-500/20';
      case 'low': return 'text-blue-400 bg-blue-500/20';
      default: return 'text-gray-400 bg-gray-500/20';
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-500"></div>
        <span className="ml-3 text-slate-400">Loading AI Evolution Engine...</span>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3">
            <span className="text-3xl">🧠</span>
            AI Evolution Engine
          </h1>
          <p className="text-slate-400 mt-1">
            Autonomous security updates keeping Anchor ahead of threats
          </p>
        </div>
        <div className="flex gap-3">
          <button
            onClick={bootstrapEngine}
            disabled={isBootstrapping || isEvolving}
            className={`px-6 py-3 rounded-lg font-semibold transition-all ${
              isBootstrapping
                ? 'bg-gray-600 cursor-not-allowed'
                : 'bg-gradient-to-r from-red-600 to-orange-500 hover:from-red-500 hover:to-orange-400'
            } text-white shadow-lg`}
          >
            {isBootstrapping ? (
              <span className="flex items-center gap-2">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                Bootstrapping...
              </span>
            ) : (
              'Bootstrap (Nuclear)'
            )}
          </button>
          <button
            onClick={triggerEvolution}
            disabled={isEvolving || isBootstrapping}
            className={`px-6 py-3 rounded-lg font-semibold transition-all ${
              isEvolving
                ? 'bg-gray-600 cursor-not-allowed'
                : 'bg-gradient-to-r from-purple-600 to-cyan-500 hover:from-purple-500 hover:to-cyan-400'
            } text-white shadow-lg`}
          >
            {isEvolving ? (
              <span className="flex items-center gap-2">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                Evolving...
              </span>
            ) : (
              'Trigger Evolution Cycle'
            )}
          </button>
        </div>
      </div>

      {/* Live Stats Bar */}
      <div className="bg-gradient-to-r from-slate-800 to-slate-900 rounded-xl p-4 border border-purple-500/30">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <span className={`w-3 h-3 rounded-full ${isConnected ? 'bg-green-500 animate-pulse' : 'bg-red-500'}`}></span>
              <span className={`text-sm font-medium ${isConnected ? 'text-green-400' : 'text-red-400'}`}>
                {isConnected ? 'LIVE' : 'OFFLINE'}
              </span>
            </div>
            <div className="h-6 w-px bg-slate-600"></div>
            <div className="flex gap-6 text-sm">
              <span className="text-slate-400">Threats: <span className="text-cyan-400 font-bold">{liveStats.totalThreats}</span></span>
              <span className="text-slate-400">Rules: <span className="text-purple-400 font-bold">{liveStats.totalRules}</span></span>
              <span className="text-slate-400">AI Analyses: <span className="text-green-400 font-bold">{liveStats.aiAnalysisCount}</span></span>
              <span className="text-slate-400">Score: <span className="text-yellow-400 font-bold">{liveStats.competitiveScore}%</span></span>
            </div>
          </div>
          <div className="text-xs text-slate-500 font-mono">
            {liveEvents[0]?.timestamp ? new Date(liveEvents[0].timestamp).toLocaleTimeString() : '--:--:--'}
          </div>
        </div>
      </div>

      {/* Status Cards */}
      {status && (
        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
          <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
            <div className="text-2xl font-bold text-cyan-400">{status.threatsProcessed}</div>
            <div className="text-sm text-slate-400">Threats Processed</div>
          </div>
          <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
            <div className="text-2xl font-bold text-purple-400">{status.rulesGenerated}</div>
            <div className="text-sm text-slate-400">Rules Generated</div>
          </div>
          <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
            <div className="text-2xl font-bold text-green-400">{status.updatesApplied}</div>
            <div className="text-sm text-slate-400">Updates Applied</div>
          </div>
          <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
            <div className="text-2xl font-bold text-yellow-400">{status.competitiveScore}%</div>
            <div className="text-sm text-slate-400">Competitive Score</div>
          </div>
          <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
            <div className="text-sm font-mono text-slate-300">
              {new Date(status.lastUpdate).toLocaleTimeString()}
            </div>
            <div className="text-sm text-slate-400">Last Update</div>
          </div>
          <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
            <div className="text-sm font-mono text-slate-300">
              {new Date(status.nextScheduledUpdate).toLocaleTimeString()}
            </div>
            <div className="text-sm text-slate-400">Next Update</div>
          </div>
        </div>
      )}

      {/* Tabs */}
      <div className="flex gap-2 border-b border-slate-700 pb-2">
        {(['live', 'overview', 'threats', 'rules', 'feeds', 'generate'] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`px-4 py-2 rounded-lg font-medium transition-all ${
              activeTab === tab
                ? tab === 'live' ? 'bg-green-600 text-white' : 'bg-purple-600 text-white'
                : 'text-slate-400 hover:text-white hover:bg-slate-700'
            }`}
          >
            {tab === 'live' && 'Live Feed'}
            {tab === 'overview' && 'Overview'}
            {tab === 'threats' && 'Threats'}
            {tab === 'rules' && 'Rules'}
            {tab === 'feeds' && 'Feeds'}
            {tab === 'generate' && 'Generate'}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="bg-slate-800/30 rounded-xl p-6 border border-slate-700">
        {/* LIVE FEED TAB */}
        {activeTab === 'live' && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold text-white flex items-center gap-2">
                <span className={`w-2.5 h-2.5 rounded-full ${isConnected ? 'bg-green-500 animate-pulse' : 'bg-red-500'}`}></span>
                Real-Time Evolution Feed
              </h3>
              <div className="flex items-center gap-3">
                <span className="text-xs text-slate-500">{liveEvents.length} events</span>
                <button
                  onClick={() => setLiveEvents([])}
                  className="px-3 py-1 text-xs bg-slate-700 hover:bg-slate-600 text-slate-300 rounded transition-all"
                >
                  Clear
                </button>
              </div>
            </div>
            
            <div ref={liveLogRef} className="space-y-1.5 max-h-[600px] overflow-y-auto font-mono text-sm">
              {liveEvents.map((event, i) => {
                const eventConfig = getEventConfig(event.type);
                return (
                  <div key={i} className={`flex items-start gap-3 p-2.5 rounded-lg border ${eventConfig.border} ${eventConfig.bg} transition-all ${i === 0 ? 'ring-1 ring-inset ' + eventConfig.ring : ''}`}>
                    <span className="text-lg flex-shrink-0 mt-0.5">{eventConfig.icon}</span>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className={`text-xs font-bold uppercase tracking-wider ${eventConfig.label}`}>{event.type.replace(/_/g, ' ')}</span>
                        <span className="text-[10px] text-slate-500">{new Date(event.timestamp).toLocaleTimeString()}</span>
                      </div>
                      <div className="text-xs text-slate-300 mt-0.5 truncate">
                        {formatEventData(event)}
                      </div>
                    </div>
                    {(event.data as any)?.severity && (
                      <span className={`px-1.5 py-0.5 rounded text-[10px] font-bold flex-shrink-0 ${getSeverityColor((event.data as any).severity)}`}>
                        {((event.data as any).severity as string).toUpperCase()}
                      </span>
                    )}
                  </div>
                );
              })}
              {liveEvents.length === 0 && (
                <div className="text-slate-500 text-center py-16">
                  <div className="text-4xl mb-3">📡</div>
                  <div className="text-lg">Waiting for evolution events...</div>
                  <div className="text-sm mt-2">Trigger an evolution cycle or hit Bootstrap to see real-time data flow</div>
                </div>
              )}
            </div>
          </div>
        )}

        {/* OVERVIEW TAB */}
        {activeTab === 'overview' && (
          <div className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Evolution Log */}
              <div>
                <h3 className="text-lg font-semibold text-white mb-4">Evolution Activity</h3>
                <div className="space-y-2 max-h-64 overflow-y-auto">
                  {evolutionLog.slice(0, 10).map((entry, i) => (
                    <div key={i} className="flex items-start gap-3 p-3 bg-slate-700/30 rounded-lg">
                      <span className={entry.aiGenerated ? 'text-purple-400' : 'text-cyan-400'}>
                        {entry.aiGenerated ? '🤖' : '👤'}
                      </span>
                      <div className="flex-1">
                        <div className="text-sm font-medium text-white">{entry.action}</div>
                        <div className="text-xs text-slate-400">{entry.details}</div>
                        <div className="text-xs text-slate-500 mt-1">
                          {new Date(entry.timestamp).toLocaleString()}
                        </div>
                      </div>
                    </div>
                  ))}
                  {evolutionLog.length === 0 && (
                    <div className="text-slate-500 text-center py-8">
                      No evolution activity yet. Trigger an evolution cycle to start.
                    </div>
                  )}
                </div>
              </div>

              {/* Competitive Analysis */}
              <div>
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-white">Competitive Analysis</h3>
                  <button
                    onClick={loadCompetitiveAnalysis}
                    className="px-3 py-1 text-sm bg-purple-600/30 hover:bg-purple-600/50 text-purple-300 rounded-lg transition-all"
                  >
                    Analyze Market
                  </button>
                </div>
                {competitiveAnalysis ? (
                  <div className="space-y-3">
                    <div>
                      <div className="text-sm text-slate-400 mb-2">Emerging Threats:</div>
                      <div className="flex flex-wrap gap-2">
                        {competitiveAnalysis.emergingThreats?.slice(0, 5).map((t: string, i: number) => (
                          <span key={i} className="px-2 py-1 bg-red-500/20 text-red-300 rounded text-xs">
                            {t.substring(0, 40)}...
                          </span>
                        ))}
                      </div>
                    </div>
                    <div>
                      <div className="text-sm text-slate-400 mb-2">Anchor Advantages:</div>
                      <div className="flex flex-wrap gap-2">
                        {competitiveAnalysis.anchorAdvantages?.map((a: string, i: number) => (
                          <span key={i} className="px-2 py-1 bg-green-500/20 text-green-300 rounded text-xs">
                            {a}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="text-slate-500 text-center py-8">
                    Click &quot;Analyze Market&quot; to see competitive landscape
                  </div>
                )}
              </div>
            </div>

            {/* AI Query */}
            <div>
              <h3 className="text-lg font-semibold text-white mb-4">AI Security Analysis</h3>
              <div className="flex gap-3">
                <input
                  type="text"
                  placeholder="Ask AI about any security topic..."
                  className="flex-1 px-4 py-3 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:border-purple-500 focus:outline-none"
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && (e.target as HTMLInputElement).value) {
                      analyzeCustomQuery((e.target as HTMLInputElement).value);
                    }
                  }}
                />
                <button
                  onClick={() => {
                    const input = document.querySelector('input[placeholder*="Ask AI"]') as HTMLInputElement;
                    if (input?.value) analyzeCustomQuery(input.value);
                  }}
                  className="px-6 py-3 bg-purple-600 hover:bg-purple-500 text-white rounded-lg font-medium transition-all"
                >
                  Analyze
                </button>
              </div>
              {analysisResult && (
                <div className="mt-4 p-4 bg-slate-700/50 rounded-lg border border-purple-500/30">
                  <pre className="text-sm text-slate-300 whitespace-pre-wrap font-mono">
                    {analysisResult}
                  </pre>
                </div>
              )}
            </div>
          </div>
        )}

        {/* THREATS TAB */}
        {activeTab === 'threats' && (
          <div>
            <h3 className="text-lg font-semibold text-white mb-4">Processed Threats ({threats.length})</h3>
            <div className="space-y-3 max-h-[500px] overflow-y-auto">
              {threats.map(threat => (
                <div key={threat.id} className="p-4 bg-slate-700/30 rounded-lg border border-slate-600">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-3">
                        <span className={`px-2 py-1 rounded text-xs font-semibold ${getSeverityColor(threat.severity)}`}>
                          {threat.severity.toUpperCase()}
                        </span>
                        <span className="text-sm text-slate-400">{threat.source}</span>
                        <span className="text-xs text-slate-500">
                          {new Date(threat.timestamp).toLocaleDateString()}
                        </span>
                      </div>
                      <div className="text-white font-medium mt-2">{threat.title}</div>
                      <div className="text-sm text-slate-400 mt-1 line-clamp-2">{threat.description}</div>
                    </div>
                    <div className="flex items-center gap-2">
                      {threat.processed && (
                        <span className="px-2 py-1 bg-green-500/20 text-green-300 rounded text-xs">
                          Processed
                        </span>
                      )}
                      {threat.aiAnalysis && (
                        <span className="px-2 py-1 bg-purple-500/20 text-purple-300 rounded text-xs">
                          AI Analyzed
                        </span>
                      )}
                    </div>
                  </div>
                  {threat.aiAnalysis && (
                    <div className="mt-3 p-3 bg-slate-800/50 rounded text-sm text-slate-300">
                      <div className="text-xs text-purple-400 mb-1">AI Analysis:</div>
                      {threat.aiAnalysis.substring(0, 200)}...
                    </div>
                  )}
                </div>
              ))}
              {threats.length === 0 && (
                <div className="text-slate-500 text-center py-8">
                  No threats processed yet. Trigger an evolution cycle.
                </div>
              )}
            </div>
          </div>
        )}

        {/* RULES TAB */}
        {activeTab === 'rules' && (
          <div>
            <h3 className="text-lg font-semibold text-white mb-4">
              Auto-Generated Detection Rules ({rules.filter(r => r.autoGenerated).length} / {rules.length})
            </h3>
            <div className="space-y-3 max-h-[500px] overflow-y-auto">
              {rules.map(rule => (
                <div key={rule.id} className="p-4 bg-slate-700/30 rounded-lg border border-slate-600">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-3">
                        <span className={`px-2 py-1 rounded text-xs font-semibold ${getSeverityColor(rule.severity)}`}>
                          {rule.severity.toUpperCase()}
                        </span>
                        <span className="text-sm text-slate-400">{rule.type}</span>
                        {rule.autoGenerated && (
                          <span className="px-2 py-1 bg-purple-500/20 text-purple-300 rounded text-xs">
                            AI Generated
                          </span>
                        )}
                      </div>
                      <div className="text-white font-medium mt-2">{rule.name}</div>
                      {rule.pattern && (
                        <div className="mt-2 p-2 bg-slate-800 rounded text-xs font-mono text-slate-400">
                          {rule.pattern.substring(0, 100)}...
                        </div>
                      )}
                      <div className="flex items-center gap-4 mt-2 text-xs text-slate-500">
                        <span>Effectiveness: {rule.effectiveness}%</span>
                        <span>Created: {new Date(rule.createdAt).toLocaleDateString()}</span>
                      </div>
                    </div>
                    <button
                      onClick={() => toggleRule(rule.id, rule.enabled)}
                      className={`px-4 py-2 rounded-lg font-medium transition-all ${
                        rule.enabled
                          ? 'bg-green-600/30 text-green-300 hover:bg-green-600/50'
                          : 'bg-slate-600/30 text-slate-400 hover:bg-slate-600/50'
                      }`}
                    >
                      {rule.enabled ? 'Enabled' : 'Disabled'}
                    </button>
                  </div>
                </div>
              ))}
              {rules.length === 0 && (
                <div className="text-slate-500 text-center py-8">
                  No detection rules generated yet. Process threats to auto-generate rules.
                </div>
              )}
            </div>
          </div>
        )}

        {/* FEEDS TAB */}
        {activeTab === 'feeds' && (
          <div>
            <h3 className="text-lg font-semibold text-white mb-4">Threat Intelligence Feeds</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {[
                { id: 'nvd', name: 'NVD CVE Feed', type: 'CVE', status: 'active', icon: '🏛️' },
                { id: 'cisa-kev', name: 'CISA KEV', type: 'Exploit', status: 'active', icon: '🚨' },
                { id: 'mitre-attack', name: 'MITRE ATT&CK', type: 'APT', status: 'active', icon: '🎯' },
                { id: 'abuse-ch', name: 'Abuse.ch Malware', type: 'Malware', status: 'active', icon: '🦠' },
                { id: 'otx', name: 'AlienVault OTX', type: 'IOC', status: 'active', icon: '👽' },
                { id: 'first-epss', name: 'FIRST EPSS', type: 'CVE Score', status: 'active', icon: '📊' },
              ].map(feed => (
                <div key={feed.id} className="p-4 bg-slate-700/30 rounded-lg border border-slate-600">
                  <div className="flex items-center gap-3">
                    <span className="text-2xl">{feed.icon}</span>
                    <div>
                      <div className="text-white font-medium">{feed.name}</div>
                      <div className="text-sm text-slate-400">{feed.type}</div>
                    </div>
                  </div>
                  <div className="mt-3 flex items-center justify-between">
                    <span className={`px-2 py-1 rounded text-xs ${
                      feed.status === 'active' 
                        ? 'bg-green-500/20 text-green-300' 
                        : 'bg-red-500/20 text-red-300'
                    }`}>
                      {feed.status === 'active' ? 'Active' : 'Inactive'}
                    </span>
                    <span className="text-xs text-slate-500">Auto-updating</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* GENERATE TAB */}
        {activeTab === 'generate' && (
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-white mb-4">Generate New Security Module</h3>
              <p className="text-slate-400 mb-4">
                Describe a security capability you need, and the AI will generate the module specification.
              </p>
              <div className="flex gap-3">
                <input
                  type="text"
                  value={moduleRequirement}
                  onChange={(e) => setModuleRequirement(e.target.value)}
                  placeholder="e.g., 'Detect cryptocurrency mining attacks in containerized environments'"
                  className="flex-1 px-4 py-3 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:border-purple-500 focus:outline-none"
                />
                <button
                  onClick={generateModule}
                  className="px-6 py-3 bg-gradient-to-r from-purple-600 to-cyan-500 hover:from-purple-500 hover:to-cyan-400 text-white rounded-lg font-medium transition-all"
                >
                  Generate
                </button>
              </div>
            </div>

            {generatedModule && (
              <div className="p-6 bg-slate-700/50 rounded-xl border border-purple-500/30">
                <div className="flex items-center gap-3 mb-4">
                  <span className="text-2xl">📦</span>
                  <div>
                    <div className="text-xl font-bold text-white">{generatedModule.moduleName}</div>
                    <div className="text-sm text-slate-400">{generatedModule.description}</div>
                  </div>
                </div>

                <div className="mt-4">
                  <div className="text-sm font-medium text-slate-300 mb-2">Generated Code:</div>
                  <pre className="p-4 bg-slate-800 rounded-lg text-xs font-mono text-green-400 overflow-x-auto">
                    {generatedModule.pseudoCode}
                  </pre>
                </div>

                {generatedModule.integrationPoints && (
                  <div className="mt-4">
                    <div className="text-sm font-medium text-slate-300 mb-2">Integration Points:</div>
                    <div className="flex flex-wrap gap-2">
                      {generatedModule.integrationPoints.map((point: string, i: number) => (
                        <span key={i} className="px-3 py-1 bg-cyan-500/20 text-cyan-300 rounded-lg text-sm">
                          {point}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="text-center text-sm text-slate-500">
        <span className="inline-flex items-center gap-2">
          <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
          AI Evolution Engine is continuously monitoring the threat landscape
        </span>
      </div>
    </div>
  );
}
